services:
  - type: web
    name: focuslock-backend
    env: node
    rootDir: backend
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
